CREATE TABLE IF NOT EXISTS upgrade (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    upgrate_name VARCHAR(50) NOT NULL,
    description TEXT,
    cost VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    unit_id VARCHAR(200)
    )